"""Investigation report contract — the assembled deliverable for maritime authorities."""

from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field

from app.schemas.detection import SpillDetection
from app.schemas.environmental import EnvironmentalImpact
from app.schemas.investigation import SuspectRanking
from app.schemas.ocean_intelligence import ForecastResult, HindcastResult

SpillCause = Literal[
    "illegal-bilge-dumping", "cargo-leak", "tanker-collision", "pipeline-rupture",
    "offshore-drilling-incident", "maintenance-discharge", "unknown",
]


class CauseAssessment(BaseModel):
    cause: SpillCause
    probability: float = Field(ge=0, le=1)
    supporting_evidence: list[str]
    alternatives: dict[str, float] = Field(default_factory=dict)
    #: confidence (0..1) that the spill came from each broad cause category —
    #: Shipping accident / Offshore drilling / Pipeline or storage failure /
    #: Human error / Natural disaster / Intentional dumping
    category_confidence: dict[str, float] = Field(default_factory=dict)


class ReportSection(BaseModel):
    key: str
    title: str
    body_markdown: str


class InvestigationReport(BaseModel):
    id: str
    detection_id: str
    investigation_id: str | None = None
    incident_id: str | None = None
    generated_at: datetime
    title: str
    executive_summary: str
    cause: CauseAssessment
    lead_suspect_mmsi: str | None = None
    detection: SpillDetection
    hindcast: HindcastResult
    forecast: ForecastResult
    suspects: SuspectRanking
    environmental: EnvironmentalImpact | None = None
    sections: list[ReportSection]
    disclaimer: str = (
        "Generated by Nero from remote-sensing, oceanographic and AIS data. "
        "Findings are decision-support estimates and require corroboration before "
        "enforcement action."
    )


class ReportRequest(BaseModel):
    detection_id: str
    investigation_id: str | None = None
    format: Literal["json", "html"] = "json"
